### ISSUE TITLE
Test with firefox

### ISSUE THREAD

**Issue by s2oBCN** [collectai/retractor#65]
Hi! And thank you very much for share this project!

I was trying to use the project with a "real browser". But before start I wanted to be sure that the tests of the project pass with another browser. So I:
* Cloned the git project. 
* Executed npm install and npm run test with all tests passed OK.
* Updated the dependence "selenium-webdriver" to "^3. 0.1", because in "2.53.1" it has problems connecting to the selenium server
* Finally changed the file test/index. is to use FF "driver = new webdriver. Builder (). for Browser ('Firefox'). build ();"
But then I have this results when I execute the tests:
Retractor
✓ should return a function with a DisplayName (43ms) to-do app
✓ should load  the demo page
    ✓ should find a single element
    1) should find a single element by props
    ✓ should find all elements
    2) should limit results to the given scope

  4 passing (4s)
  2 failing

  1) todo app should find a single element by props:
expected Promise when fulfilled to be a function WebElement( /*...*/ ) { /*...*/ }
  Promise unexpectedly rejected with TypeError('Custom locator did not return a WebElement')

      at node_modules/selenium-webdriver/lib/webdriver.js:1042:15
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1366:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2813:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) todo app should limit results to the given scope:
     
expected Promise to be fulfilled with 'Use Retractor Scoping'
  expected Promise to be fulfilled
    Promise unexpectedly rejected with TypeError('Custom locator did not return a WebElement')
      at node_modules/selenium-webdriver/lib/webdriver.js:1042:15
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1366:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2813:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebElement.getText()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:816:17)
      at WebElementPromise.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
      at WebElementPromise.getText (node_modules/selenium-webdriver/lib/webdriver.js:2185:17)
      at Context.<anonymous> (test/index.js:77:22)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1366:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2813:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)

Do you know how to solve this problem?

Thank  you!

**Comment by s2oBCN** [comment]
Hi! Finally, I had time to see this issue and I tested with the WebDriver 2.53 + a FF version < 45. And it was executed without errors.
So the problem could be related to the last version of Selenium and FF.
